### ISSUE TITLE
alphaflow not working -- keyError: 'ptm'

### ISSUE THREAD

**Issue by marinaort** [bjing2016/alphaflow#33]
I had been running alphaflow in an environment for the last months and it was working fine. This weekend I had not been able to run it. I have been getting this error:

[INFO] Loading the model
[INFO] Model has been loaded
  0%|                     | 0/50 [00:08<?, ?it/s]
Traceback (most recent call last):
  File "/GIT/alphaflow/predict.py", line 175, in <module>
    main()
  File "/alphaflow/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/GIT/alphaflow/predict.py", line 129, in main
    dat = {col: dat[col] for col in cols}
  File "/GIT/alphaflow/predict.py", line 129, in <dictcomp>
    dat = {col: dat[col] for col in cols}
KeyError: 'ptm'

Another issue I found while running alphaflow is that in the file templates.py in lines 88 and 89 it is ussing np.object but a warning is displayed because in newer versions of numpy this doesn't exists and it recommends to change that lines from np.object to object.

**Comment by bjing2016** [comment]
Hi Marina,
It looks like there was an issue with the most recent PR --- could you pull and see if it's working now?
