### ISSUE TITLE
Chain Index returns NoneType

### ISSUE THREAD

**Issue by JoshuaEPSamuel** [bjing2016/alphaflow#41]
I've been trying to run a test using the esmflow_md_templates_base_202402 model, but it is having issues writing the output to a PDB. This has been the case whether I run the splits/atlast_test.csv or my own test input. Seems to be an issue in the Openfold library
```
Traceback (most recent call last):
  File "/home/josh/github_repos/alphaflow/predict.py", line 133, in <module>
    main()
  File "/home/josh/miniconda3/envs/openfold_env/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/josh/github_repos/alphaflow/predict.py", line 127, in main
    f.write(protein.prots_to_pdb(result))
  File "/home/josh/github_repos/alphaflow/alphaflow/utils/protein.py", line 163, in prots_to_pdb
    prot = to_pdb(prot)
  File "/home/josh/github_repos/alphaflow/openfold/np/protein.py", line 341, in to_pdb
    chain_index = prot.chain_index.astype(np.int32)
AttributeError: 'NoneType' object has no attribute 'astype'
```

Here it seems to show that the chain_index attribute in the Protein class is Optional and can be None:
https://github.com/aqlaboratory/openfold/blob/23cf2f6107bf5753cfb12ce05895d66f2135d9cd/openfold/np/protein.py#L68C1-L69C45

However, most of the lines calling `chain_index` in the function `to_pdb()` break if chain_index does not exist/is None

**Comment by agheeraert** [comment]
I had the exact same issue, did you build using the `103d037` commit of openfold?
To solve it I had to change line 80 in `utils/protein.py` to             `chain_index=output["chain_index"][i] if "chain_index" in output else np.repeat([1], len(seqres))`

**Comment by lisaotten** [comment]
Is there a solution to this problem?
I encountered the same and added 
if prot.chain_index is None:
            prot.chain_index = np.zeros(
                prot.aatype.shape[0], dtype=np.int32
            )

to the prots_to_pdb function and it seemed to work, but now the coordinates in the pdb file make no sense.
